apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: example-entrypoint-with-param
spec:
  resources:
  - name: gitresource
    type: git
  - name: sharedcluster
    type: cluster
  tasks:
    - name: example-entrypoint
      taskRef:
        name: example-entrypoint
      resources:
        inputs:
        - name: gitresource
          resource: gitresource
        - name: sharedcluster
          resource: sharedcluster
